window.MAIHL_DATA = {
  players: [
    {
      key: "Muhummud",
      fullName: "Muhummud Teli",
      shortName: "Muhummud",
      initials: "MT",
      jersey: "88",
      countryFlag: "🇨🇦",
      overall: 90,
      gp: 2,
      wins: 1,
      losses: 1,
      goals: 13,
      shots: 35,
      shootingPct: "37.1%",
      saves: 20,
      savePct: ".606",
      ga: 13,
      gaa: "6.50",
      plusMinus: 0,
      goalsTrend: [9, 4, 0, 0, 0],
      shotsTrend: [21, 14, 0, 0, 0],
      winStreakTrend: [1, 0, 0, 0, 0]
    },
    {
      key: "Ahmed",
      fullName: "Ahmed Kasujee",
      shortName: "Ahmed",
      initials: "AK",
      jersey: "22",
      countryFlag: "🇨🇦",
      overall: 92,
      gp: 2,
      wins: 1,
      losses: 1,
      goals: 13,
      shots: 33,
      shootingPct: "39.4%",
      saves: 22,
      savePct: ".629",
      ga: 13,
      gaa: "6.50",
      plusMinus: 0,
      goalsTrend: [6, 7, 0, 0, 0],
      shotsTrend: [21, 12, 0, 0, 0],
      winStreakTrend: [0, 1, 0, 0, 0]
    },
    {
      key: "Bilal",
      fullName: "Bilal Govani",
      shortName: "Bilal",
      initials: "BG",
      jersey: "N/A",
      countryFlag: "🇨🇦",
      overall: null,
      gp: 0,
      wins: 0,
      losses: 0,
      goals: 0,
      shots: 0,
      shootingPct: "0.0%",
      saves: 0,
      savePct: ".000",
      ga: 0,
      gaa: "0.00",
      plusMinus: 0,
      goalsTrend: [0, 0, 0, 0, 0],
      shotsTrend: [0, 0, 0, 0, 0],
      winStreakTrend: [0, 0, 0, 0, 0]
    },
    {
      key: "Ismail",
      fullName: "Ismail Kayka",
      shortName: "Ismail",
      initials: "IK",
      jersey: "21",
      countryFlag: "🇨🇦",
      overall: null,
      gp: 0,
      wins: 0,
      losses: 0,
      goals: 0,
      shots: 0,
      shootingPct: "0.0%",
      saves: 0,
      savePct: ".000",
      ga: 0,
      gaa: "0.00",
      plusMinus: 0,
      goalsTrend: [0, 0, 0, 0, 0],
      shotsTrend: [0, 0, 0, 0, 0],
      winStreakTrend: [0, 0, 0, 0, 0]
    },
    {
      key: "Husaifa",
      fullName: "Husaifa Khotwa",
      shortName: "Husaifa",
      initials: "HK",
      jersey: "N/A",
      countryFlag: "🇨🇦",
      overall: null,
      gp: 0,
      wins: 0,
      losses: 0,
      goals: 0,
      shots: 0,
      shootingPct: "0.0%",
      saves: 0,
      savePct: ".000",
      ga: 0,
      gaa: "0.00",
      plusMinus: 0,
      goalsTrend: [0, 0, 0, 0, 0],
      shotsTrend: [0, 0, 0, 0, 0],
      winStreakTrend: [0, 0, 0, 0, 0]
    },
    {
      key: "Mohammed",
      fullName: "Mohammed Taliya",
      shortName: "Mohammed",
      initials: "MTA",
      jersey: "N/A",
      countryFlag: "🇨🇦",
      overall: null,
      gp: 0,
      wins: 0,
      losses: 0,
      goals: 0,
      shots: 0,
      shootingPct: "0.0%",
      saves: 0,
      savePct: ".000",
      ga: 0,
      gaa: "0.00",
      plusMinus: 0,
      goalsTrend: [0, 0, 0, 0, 0],
      shotsTrend: [0, 0, 0, 0, 0],
      winStreakTrend: [0, 0, 0, 0, 0]
    }
  ],
  games: [
    {
      id: "1",
      game: "Game 1",
      date: "November 15, 2025",
      matchup: "Ahmed vs Muhummud",
      players: ["Ahmed", "Muhummud"],
      displayPlayers: ["Muhummud", "Ahmed"],
      scoreOrder: ["Muhummud", "Ahmed"],
      winner: "Muhummud",
      finalScore: "Muhummud 9 - 6 Ahmed",
      status: "Played",
      stats: {
        Muhummud: { goals: 9, shots: 21, shootingPct: "42.9%", ga: 6, saves: 15, savePct: ".714", plusMinus: "+3" },
        Ahmed: { goals: 6, shots: 21, shootingPct: "28.6%", ga: 9, saves: 12, savePct: ".571", plusMinus: "-3" }
      },
      goals: [
        { label: "Goal 1", scorer: "Muhummud", score: "1-0" },
        { label: "Goal 2", scorer: "Muhummud", score: "2-0" },
        { label: "Goal 3", scorer: "Ahmed", score: "2-1" },
        { label: "Goal 4", scorer: "Ahmed", score: "2-2" },
        { label: "Goal 5", scorer: "Ahmed", score: "2-3" },
        { label: "Goal 6", scorer: "Muhummud", score: "3-3" },
        { label: "Goal 7", scorer: "Muhummud", score: "4-3" },
        { label: "Goal 8", scorer: "Ahmed", score: "4-4" },
        { label: "Goal 9", scorer: "Ahmed", score: "4-5" },
        { label: "Goal 10", scorer: "Muhummud", score: "5-5" },
        { label: "Goal 11", scorer: "Muhummud", score: "6-5" },
        { label: "Goal 12", scorer: "Ahmed", score: "6-6" },
        { label: "Goal 13", scorer: "Muhummud", score: "7-6" },
        { label: "Goal 14", scorer: "Muhummud", score: "8-6" },
        { label: "Goal 15", scorer: "Muhummud", score: "9-6" }
      ]
    },
    {
      id: "2",
      game: "Game 2",
      date: "October 18, 2025",
      matchup: "Muhummud vs Ahmed",
      players: ["Muhummud", "Ahmed"],
      displayPlayers: ["Muhummud", "Ahmed"],
      scoreOrder: ["Ahmed", "Muhummud"],
      winner: "Ahmed",
      finalScore: "Ahmed 7 - 4 Muhummud",
      status: "Played",
      stats: {
        Muhummud: { goals: 4, shots: 14, shootingPct: "28.6%", ga: 7, saves: 5, savePct: ".417", plusMinus: "-3" },
        Ahmed: { goals: 7, shots: 12, shootingPct: "58.3%", ga: 4, saves: 10, savePct: ".714", plusMinus: "+3" }
      },
      goals: [
        { label: "Goal 1", scorer: "Ahmed", score: "1-0" },
        { label: "Goal 2", scorer: "Ahmed", score: "2-0" },
        { label: "Goal 3", scorer: "Ahmed", score: "3-0" },
        { label: "Goal 4", scorer: "Muhummud", score: "3-1" },
        { label: "Goal 5", scorer: "Ahmed", score: "4-1" },
        { label: "Goal 6", scorer: "Ahmed", score: "5-1" },
        { label: "Goal 7", scorer: "Muhummud", score: "5-2" },
        { label: "Goal 8", scorer: "Ahmed", score: "6-2" },
        { label: "Goal 9", scorer: "Ahmed", score: "7-2" },
        { label: "Goal 10", scorer: "Muhummud", score: "7-3" },
        { label: "Goal 11", scorer: "Muhummud", score: "7-4" }
      ]
    },
    {
      id: "3",
      game: "Game 3",
      date: "Date TBD",
      matchup: "Muhummud vs Ahmed",
      players: ["Muhummud", "Ahmed"],
      displayPlayers: ["Muhummud", "Ahmed"],
      scoreOrder: ["Muhummud", "Ahmed"],
      winner: "TBD",
      finalScore: "TBD",
      status: "Upcoming",
      stats: {},
      goals: []
    },
    { id: "4", game: "Game 4", date: "Date TBD", matchup: "Matchup TBD", players: ["TBD", "TBD"], displayPlayers: ["TBD", "TBD"], scoreOrder: ["TBD", "TBD"], winner: "TBD", finalScore: "TBD", status: "Upcoming", stats: {}, goals: [] },
    { id: "5", game: "Game 5", date: "Date TBD", matchup: "Matchup TBD", players: ["TBD", "TBD"], displayPlayers: ["TBD", "TBD"], scoreOrder: ["TBD", "TBD"], winner: "TBD", finalScore: "TBD", status: "Upcoming", stats: {}, goals: [] },
    { id: "6", game: "Game 6", date: "Date TBD", matchup: "Matchup TBD", players: ["TBD", "TBD"], displayPlayers: ["TBD", "TBD"], scoreOrder: ["TBD", "TBD"], winner: "TBD", finalScore: "TBD", status: "Upcoming", stats: {}, goals: [] },
    { id: "7", game: "Game 7", date: "Date TBD", matchup: "Matchup TBD", players: ["TBD", "TBD"], displayPlayers: ["TBD", "TBD"], scoreOrder: ["TBD", "TBD"], winner: "TBD", finalScore: "TBD", status: "Upcoming", stats: {}, goals: [] }
  ],
  injuries: [
    { id: "1", label: "Injury 1", gameId: "1", game: "Game 1", date: "November 15, 2025", player: "Ahmed", injury: "Right Wrist Injury", status: "Fully healed" },
    { id: "2", label: "Injury 2", gameId: "2", game: "Game 2", date: "October 18, 2025", player: "Muhummud", injury: "Left Foot Injury (cramp)", status: "Fully healed" }
  ],
  awardHistory: [],
  labels: ["Game 1", "Game 2", "Game 3", "Game 4", "Game 5"]
};
